version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "makingChangeCFStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-t72lepebh46v"
s3_prefix = "makingChangeCFStack"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
