version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HelloWikiStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-t72lepebh46v"
s3_prefix = "HelloWikiStack"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["HelloWorldFunction=908357555608.dkr.ecr.us-west-2.amazonaws.com/hellowikistack518a3dad/helloworldfunction19d43fc4repo"]
